name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version of the app'
        default: 'dev'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: "${{ inputs.version }}"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Build app
      run: |
        bash tools/build.bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: fdw
        path: build/dist/fdw
